### ISSUE TITLE
Align on one name?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#105]
We're calling the project "The docassemble AssemblyLine Project" on the front page and title of the About page, then "Suffolk LIT Lab Assembly Line Bootcamp" on the bootcamp page, then the Document Assembly Line Project in the first paragraph of the intro page. Would it be useful to align on one name? If so, what do we want to use?

**Comment by colarusso** [comment]
I've harmonized the naming. It is the project's name is the Document Assembly Line. I've changed the use of Project and Bootcamp to not be part of proper nouns. On the Bootcamp page it is referenced as the Suffolk LIT Lab's Document Assembly Line Bootcamp, but those terms are descriptive and only capitalized because they are in a title.
