### ISSUE TITLE
Explain rationale for al metadata `categories`

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#133]
Currently, it's not clear why the category id is both in the da metadata block and the al metadata object.

Code: https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/122/files#diff-e9844ac134ab71120fbe0fe1e402a83310729d794729f53fef042c5fb81f36c6R73

Comment: https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/122/files#r645821391

> I think it's so we can still view the categories of combined interviews. Not sure if there's a way to keep information from multiple metadata blocks from different interviews without this block.

It may be good to add this rationale to the docs.

**Comment by BryceStevenWilley** [comment]
When I made that comment, I was make a guess. So I did a deep dive to the primary sources to see if that was the case. I tried going back to [this commit of the Weaver](https://github.com/SuffolkLITLab/docassemble-ALWeaver/commit/096cffed8485b7905b55a9ca5ad7eb506b7b3b89) that added a comment that the `interview_metadata` block is so we can "Build the dictionary of info we want the interview to know about itself." But the [`all_variables()`](https://docassemble.org/docs/functions.html#all_variables) function has been around the whole time. However, the docassemble docs have a [large disclaimer about multiple metadata blocks](https://docassemble.org/docs/initial.html#overlapping%20metadata) so from what I can tell, the original guess in the quote above is the right reason. I'll add it as a quick note on the interview description page.

**Comment by BryceStevenWilley** [comment]
This was already added both in https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/framework/magic_variables#interview_metadata, and at https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/generated_yaml#assemblyline-metadata.

**Comment by plocket** [comment]
Is it still in the da metadata block? That can get overridden, right? Or has that part been removed? If it's able to get overridden, I'm not sure it's a good place to keep the info, especially since it's duplicate info.

**Comment by BryceStevenWilley** [comment]
It's in both: it's necessary for it to be in DA's metadata block because DA does special things with it's metadata block, like categorizing interviews, including that information in the [`/list` endpoint](https://apps-test.suffolklitlab.org/list?json=1) (in tags). It's necessary for the information to be in our metadata so it can be accessed from included interviews. TBH I'm not sure if anyone is accessing categories from a including / included interview, but I don't think we should remove it.

It is duplicate, but it's only duplicate in two places. I think there are other maintenance things making things hard up to date, not duplication.

If we do want to remove it, we should transfer this to the Weaver or Assembly Line repos, I thought the main part of this issue was just having it documented.
