### ISSUE TITLE
Make bookmark download / Resource link page 

### ISSUE THREAD

**Issue by stevejaubz** [SuffolkLITLab/docassemble-AssemblyLine-documentation#151]
- [ ] Playground
- [ ] Documentation
- [ ] ql_baseline.yml
- [ ] GitHub

**Comment by samglover** [comment]
I'm not sure what this is. Any idea, @nonprofittechy, @plocket, or @colarusso?

**Comment by nonprofittechy** [comment]
Yeah, I can guess it's meant to be a single page people can use to get to all of the most common pages they'll need.

* Apps-dev.suffolklitlab.org/playground
* GitHub.com/.../ql_baseline.yml

Etc.

It's a good idea

**Comment by samglover** [comment]
I think this exists now, mostly on the [Interview building resources page](https://assemblyline.suffolklitlab.org/docs/get_started/resources).

**Comment by plocket** [comment]
That page has some links, but not all the ones that are linked above. Though I'm not sure how one links to everyone's Playground, so that one probably won't work.

**Comment by samglover** [comment]
The LIT Lab's development server is mentioned/linked on the [Beginner's guide page](https://assemblyline.suffolklitlab.org/docs/get_started/beginners_guide). But yeah, there are at least a few other development servers out there, and I'm not sure everyone wants their server to be public.

Documentation is definitely linked on the Resources page.

All the GitHub repos are linked in a couple of places, [including the Project architecture page](https://assemblyline.suffolklitlab.org/docs/get_started/al_project_architecture#components).

There is documentation of the question library ([here, for example](https://assemblyline.suffolklitlab.org/docs/customizing_interview#understanding-the-question-library)). I think it could probably be expanded or pulled out to be its own page, but it's not missing.

I'm going to leave this closed because I don't think there's anything to do that we're not already planning to do under other issues or that falls under general improvements.
