### ISSUE TITLE
Discuss and add: PDF label documentation reference material

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#17]
Would appreciate getting input before diving in so there's less change of having to completely change it all later. This is the basic structure I'm thinking of:

## People
| PDF label | Interview order | Attachment | Document output format |
|:-|:-|:-|:-|
| user | user[0] | user[0] | **First M. Last** - name of the first user |
| other_party | other_parties[0] | other_parties[0] | **First M. Last** - name of the first other_party |

(for all reserved people)

## Other objects
| PDF label | Interview order | Attachment | Document output format |
|:-|:-|:-|:-|
| court | courts[0] | courts[0] | **Court Name** - name of first court |
| docket_number | docket_numbers[0] | docket_numbers[0] | **123456** - first docket number |

## Repeat a value in multiple places
| PDF label | Interview order | Attachment | Document output format |
|:-|:-|:-|:-|
| child__2 |  |  |  |
| child__3 |  |  |  |

## Multiple items of one category
| PDF label | Interview order | Attachment | Document output format |
|:-|:-|:-|:-|
| court2 |  |  |  |
| docket_number3 |  |  |  |

## Print all names in a group
Like people, courts, or docket numbers

| PDF label | Interview order | Attachment | Document output format |
|:-|:-|:-|:-|
| courts |  |  |  |
| docket_numbers |  |  |  |
| spouses |  |  |  |
| plaintiff3<strong>_phones</strong> | plaintiffs[2]<strong>.phone_numbers()</strong> |  |  |

## Suffixes
| PDF label | Interview order | Attachment | Document output format |
|:-|:-|:-|:-|
| parent2<strong>_name</strong> | parents<strong>.gather()</strong> | parents[1]<strong>.name</strong> | **First M. Last** - name of second parent |
| parent2<strong>_gender</strong> | parents[1]<strong>.gender</strong> | parents[1]<strong>.gender</strong> | **female** - gender of second parent |
| court<strong>_division</strong> |  |  |  |

## DOCX only
Haven't tried this yet

**Comment by nonprofittechy** [comment]
Looks pretty good. I liked your idea of using docusaurus tabs for pdf/docx, so it's one table.

I would do purpose/output before the label maybe? I.e., make current last column the first. Unless you had a specific thought there that I didn't consider.

FYI courts will be replaced with trial_court. And we should also demo how to combine item 2 with repeated item 2. But I won't comment much on missing stuff since I know this is intentionally just a small sample.

**Comment by plocket** [comment]
As I've been looking at this document again, I think I'm right in articulating that this document is about the ALWeaver and the code that it creates. Otherwise, DOCX variable stuff really belongs in the documentation about all AL vars.

**Comment by nonprofittechy** [comment]
I'm not sure I follow. Are you saying you don't want to explain docx variables, only PDF variables?

I'm not sure why an interview author cares that we're transforming the variables. They want to know how to prepare a template so that it can be run through the wizard. This document feels like the place to do that to me. Maybe changing the title will help that be clearer?

**Comment by plocket** [comment]
Sorry for the lack of clarity. The latter was more what I was going for. That is, making this a section for the weaver explicitly.

**Comment by nonprofittechy** [comment]
Not sure what for the weaver explicitly means. But as long as we focus this page on helping someone automate either a PDF or DOCX with the right variable names, I think you are totally on the right track.
