### ISSUE TITLE
Rename this repository?

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/docassemble-AssemblyLine-documentation#406]
Since the name of this project is now "the Document Assembly Line" it seems like it might make sense to rename this repository. I suggest "DocAssemblyLine" as a reasonable short form for things like repositories and filenames, which suggests DocAssemblyLine-documentation as a better name for this repository.

(FWIW, this isn't actually a docassemble extension like the other `docassemble-` repositories, so it probably doesn't need to have that prefix.)

**Comment by samglover** [comment]
@nonprofittechy or @colarusso What would be the impact of renaming this repo?

* I assume it would change the URL to suffolklitlab.org/docassemblyline-documentation and break the existing link. Where would we go to redirect that?
* Is it possible to solve #343 at the same time?

I think it's worth doing this now, if possible.

**Comment by BryceStevenWilley** [comment]
Best resource I found on this is https://shoehornwithteeth.com/ramblings/2016/12/redirecting-github-pages-after-renaming-a-repository/#Renaming_an_entire_repository.

The more important paragraph for this:

> Note: If you’re using a custom domain name (e.g. my-superb-docs.com), this should be handled without your intervention. The public URL doesn’t change at all, just the source location of the files. For everything else, however, there’s a workaround available.

So, supposedly, if we switched to `assemblyline.suffolklitlab.org` first, then changed the repo name, it wouldn't affect anything. And I _think_ that GitHub will handle redirects from a repo to it's custom domain. Not sure what happens when you change the repo name though, it might not redirect anymore. Worth trying on a different repo first to confirm.

If GitHub doesn't redirect to the custom domain after renaming the repo (i.e. redirecting from suffolk.edu/docassemble-AssemblyLine-documentation to assemblyline.suffolklitlab.org, even if the repo is named DocAssemblyLine), you could make the custom domain first and give people a few (3-5 months) to start using the new links, and then change the repo name.

**Comment by samglover** [comment]
Wow, thanks for that! Changing to a subdomain first, then the repo was my plan, but just based on what seemed most likely to work/least likely to break things.
