### ISSUE TITLE
Don't use a dropdown menu to link to the legal tech class content

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#422]
![image](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/assets/7645641/e18e4cb7-d8a1-4aa7-8676-8418d9a6df88)

The extra click here isn't right for content people will often need to switch to when on this page.

We currently call this link "Intro to Docassemble" but perhaps it should be renamed to "legal tech class" to emphasize the fact it's a different page?

This may be mooted if we integrate the two documentation sites better.

**Comment by samglover** [comment]
My preferred solution would be to treat sections of the Legal Tech Class website as a dependency and include them in this documentation website. I haven't yet investigated this, but if it is possible it would solve this problem.

Otherwise, my inclination would be to move links to external documentation to on-page content rather than taking up the main navigation with external links.
