### ISSUE TITLE
Readability: Find and replace list

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-AssemblyLine-documentation#78]
I would like to add a short find and replace list, along the lines of simple words, 
obtain -> get
receive -> get
whether -> if
such as -> like
provide -often> give
I will try to add more to this and should it go in the style guide, or?

[Then edit the checklist item starting with 'Use simple words' to 'Use simple words and find and replace the words named in this section of the content documentation. < That should be a link to the section in the content documentation that's about finding and replacing the words.]

**Comment by plocket** [comment]
I think a longer list like this might be better in the style guide doc if only because Trello checklist items are not capable of having lists in them. I've offered a second example in the 'simplify' checklist item, but we could also give a link to a particular documentation section.

Feel free to just add to the google doc for now. We will be converting the google doc to a [docusaurus doc](https://github.com/suffolkLITLab/docassemble-assemblyline-documentation) over the next couple of weeks, so I'll try to let folks know when to switch where they're editing.

**Comment by plocket** [comment]
[This is the section to add this to](https://docs.google.com/document/d/1B-_6A5OKZ0b3s8z2S14KdRQsK7ga4nmjjthJiaZMiB8/edit#heading=h.76o0xz7xuflj) in the google doc.

**Comment by plocket** [comment]
See https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/content_and_plain_language_guide/#use-simple-words
