### ISSUE TITLE
Update weaver_code_anatomy.md to use the sample PDF/DOCX and the final weaver features

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#84]

**Comment by samglover** [comment]
I don't have the necessary context, so I'll just ask if this issue should still be open.

**Comment by plocket** [comment]
Do we want an example PDF and DOCX to be part of the documentation?

**Comment by samglover** [comment]
If we already have one we can use, sure. If not, I'm not sure how helpful it would be.

For DOCX, there are already copy-and-paste examples on the DOCX page, which work just fine.

For PDF, you can't really see anything useful from just looking at a PDF. Maybe screenshots of what a properly prepared PDF looks like in the PDF editor we recommend would be more useful than an example PDF, but since there are several options that could be hard to present effectively. I'll close this for now, but I've added #475 so that idea isn't lost.
